# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0008_joinfriends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinFriends',
            new_name='JoinFriend',
        ),
    ]
