# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_join_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='joins.Join'),
        ),
    ]
